### ISSUE TITLE
Header on transaction detail quite large

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#183] opened 2021-05-15 12:57 UTC
![10D99BB4-C62C-4224-B682-2F50B7E2A755](https://user-images.githubusercontent.com/747161/118361978-e57b2080-b58d-11eb-93be-f2c41d38faf3.png)

**Comment by codeho** [comment] 2021-05-17 08:21
Duplicate of #201

**Closed by codeho** 2021-05-17 08:21 UTC
