### ISSUE TITLE
fix hover color on accept terms and service step and on connect safe step

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#173] opened 2021-05-14 11:31 UTC
<img width="935" alt="Bildschirmfoto 2021-05-14 um 13 25 35" src="https://user-images.githubusercontent.com/747161/118264364-e04ba200-b4b7-11eb-8443-756222f03667.png">

**Comment by jaensen** [comment] 2021-05-16 13:59
related #173

**Comment by codeho** [comment] 2021-05-17 08:19
Duplicate of #187

**Closed by codeho** 2021-05-17 08:19 UTC
Labels: bug
