### ISSUE TITLE
After being invited (received xDai) some user experience an error

### ISSUE THREAD

**Issue by samuelandert** [circlesland/o-platform#291] opened 2021-05-19 17:12 UTC
![436165B8-1F00-445D-A326-D91CFE4B21CC](https://user-images.githubusercontent.com/747161/118855490-19c84700-b8d6-11eb-9e0b-8a9fb7fa183c.jpeg)

**Comment by jaensen** [comment] 2021-05-20 19:16
Most likely fixed in 1c496a5 couldn't reproduce this but this was most likely due to a race condition in the safe-init code.

**Closed** 2021-05-21 11:36 UTC
Labels: PRIORITY, bug
